# Generated by Django 3.1.7 on 2021-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is ushvusdnbvsdnv'),
            preserve_default=False,
        ),
    ]
