# Generated by Django 3.1.7 on 2021-03-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qauntity',
            field=models.IntegerField(default=1),
        ),
    ]
