# Generated by Django 3.1.7 on 2021-04-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210403_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('C', 'Cash On Delivier '), ('P', 'PayPal')], default='S', max_length=1),
        ),
    ]
