# Generated by Django 3.1.7 on 2021-04-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210409_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], max_length=2),
        ),
    ]
