# Generated by Django 3.1.7 on 2021-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210409_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_name',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='The Word Inside a label'),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
