# Generated by Django 3.1.7 on 2021-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210410_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_name',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='The Word Inside a label'),
        ),
    ]
