# Generated by Django 3.1.7 on 2021-04-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_shippmentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippmentorder',
            name='delivered',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippmentorder',
            name='payment_done',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='shippmentorder',
            name='payment_done_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='shippmentorder',
            name='verify_order',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
