# Generated by Django 3.1.7 on 2021-04-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20210416_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Adresss'},
        ),
        migrations.AlterField(
            model_name='shippmentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
