# Generated by Django 3.1.7 on 2021-04-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20210416_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippmentorder',
            name='payment_done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
