# Generated by Django 3.1.7 on 2021-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippmentorder',
            name='verify_done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Available'), ('NA', 'Not Available')], default='NA', max_length=2, verbose_name='Availablity Of Product'),
        ),
    ]
