# Generated by Django 3.1.7 on 2021-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20210429_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippmentorder',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='shippmentorder',
            name='report_spam',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
