# Generated by Django 3.1.7 on 2021-05-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20210506_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(choices=[('Ah', 'Ahmednagar'), ('Ak', 'Akola'), ('Am', 'Amravati'), ('Au', 'Aurangabad'), ('Be', 'Beed'), ('Bh', 'Bhandara'), ('Bu', 'Buldhana'), ('Ch', 'Chandrapur'), ('Dh', 'Dhule'), ('Ga', 'Gadchiroli'), ('Go', 'Gondia'), ('Hi', 'Hingoli'), ('Ja', 'Jalgaon'), ('Ja', 'Jalna'), ('Ko', 'Kolhapur'), ('La', 'Latur'), ('Mu', 'Mumbai'), ('Ng', 'Nagpur'), ('Na', 'Nanded'), ('Na', 'Nandurbar'), ('Ns', 'Nashik'), ('Os', 'Osmanabad'), ('Pa', 'Parbhani'), ('Pu', 'Pune'), ('Ra', 'Raigad'), ('Rt', 'Ratnagiri'), ('Sa', 'Sangli'), ('St', 'Satara'), ('Si', 'Sindhudurg'), ('So', 'Solapur'), ('Th', 'Thane'), ('Wa', 'Washim'), ('Ya', 'Yavatmal')], default='Mu', max_length=2),
        ),
    ]
