# Generated by Django 3.2.3 on 2021-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20210514_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Online Payment'), ('C', 'Cash On Delivier ')], default='S', max_length=1),
        ),
    ]
