# Generated by Django 3.2.3 on 2021-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_billingaddress_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippmentorder',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Some Reason Why You Want To Spam This Order'),
        ),
    ]
